Update README.md
sagelga/github-achievement-cheatsheet pull request #10
Opened 2023-07-14 13:09 UTC by amch-med23

adding missing infos about 'Hearth of your sleeve' and 'Open Sourcerer' Achievement badges.

2024-01-03 08:37 UTC, dasuntheekshanagit requested changes

2024-01-03 08:37 UTC, dasuntheekshanagit commented on README.md
> +- The 'Open Sourcerer' achievement badges is not yet released to public GitHub users at the moment. (July 14th 2023).
Still unavailable to public (03/01/2024)

2024-01-03 08:37 UTC, dasuntheekshanagit commented on README.md
> +- The 'Heart On Your Sleeve' achievement badges is not yet released to public GitHub users at the moment. (July 14th 2023).
Still unavailable to public (03/01/2024)

2024-06-23 09:50 UTC, heba-mustafa59 commented
codeforces

2025-05-13 14:58 UTC, Paol0B approved these changes

2025-05-19 07:52 UTC, nareshrajkumar866 approved these changes

2025-07-01 13:02 UTC, krishna851 commented on README.md
> +- The 'Open Sourcerer' achievement badges is not yet released to public GitHub users at the moment. (July 14th 2023).
thanks for the update! could you please share the source or github annoucement confirming these badges are unreleased

2025-08-08 16:05 UTC, closed without merging